"""initial gridlock schema

Revision ID: dddaa4f5b91b
Revises: 
Create Date: 2026-09-16 05:22:30.727860
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'dddaa4f5b91b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gl_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('auth_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('persona', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('favorite_driver_id', sa.Integer(), nullable=True),
    sa.Column('favorite_constructor_id', sa.Integer(), nullable=True),
    sa.Column('public_profile', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gl_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gl_profile_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_gl_profile_username'), ['username'], unique=True)

    op.create_table('gl_score_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('constructor_id', sa.Integer(), nullable=True),
    sa.Column('asset_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_points', sa.Float(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('source_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'round_id', 'asset_ref', 'rule_code', 'source_event_id')
    )
    with op.batch_alter_table('gl_score_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gl_score_event_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gl_score_event_round_id'), ['round_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gl_score_event_season_id'), ['season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gl_score_event_session_id'), ['session_id'], unique=False)

    op.create_table('ms_circuit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ext_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ms_circuit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ms_circuit_ext_id'), ['ext_id'], unique=True)

    op.create_table('ms_data_sync_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('records', sa.Integer(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ms_season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ms_season', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ms_season_year'), ['year'], unique=True)

    op.create_table('gl_boost_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('boost_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['gl_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'boost_id', 'round_id')
    )
    with op.batch_alter_table('gl_boost_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gl_boost_usage_profile_id'), ['profile_id'], unique=False)

    op.create_table('gl_league',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('privacy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_round', sa.Integer(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('creator_profile_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_profile_id'], ['gl_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gl_league', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gl_league_code'), ['code'], unique=True)

    op.create_table('gl_refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['gl_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gl_refresh_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gl_refresh_token_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gl_refresh_token_token_hash'), ['token_hash'], unique=True)

    op.create_table('gl_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('driver_ids', sa.JSON(), nullable=True),
    sa.Column('constructor_ids', sa.JSON(), nullable=True),
    sa.Column('captain_id', sa.Integer(), nullable=True),
    sa.Column('active_boost', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('boost_driver_id', sa.Integer(), nullable=True),
    sa.Column('boost_constructor_id', sa.Integer(), nullable=True),
    sa.Column('free_transfers', sa.Integer(), nullable=False),
    sa.Column('team_value', sa.Float(), nullable=False),
    sa.Column('bank', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['gl_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gl_team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gl_team_profile_id'), ['profile_id'], unique=True)

    op.create_table('gl_team_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('driver_ids', sa.JSON(), nullable=True),
    sa.Column('constructor_ids', sa.JSON(), nullable=True),
    sa.Column('captain_id', sa.Integer(), nullable=True),
    sa.Column('active_boost', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('boost_driver_id', sa.Integer(), nullable=True),
    sa.Column('boost_constructor_id', sa.Integer(), nullable=True),
    sa.Column('prices', sa.JSON(), nullable=True),
    sa.Column('team_value', sa.Float(), nullable=False),
    sa.Column('transfers_made', sa.Integer(), nullable=False),
    sa.Column('transfer_penalty', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['gl_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'round_id')
    )
    with op.batch_alter_table('gl_team_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gl_team_snapshot_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gl_team_snapshot_round_id'), ['round_id'], unique=False)

    op.create_table('gl_transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sold_id', sa.Integer(), nullable=True),
    sa.Column('bought_id', sa.Integer(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('free', sa.Boolean(), nullable=False),
    sa.Column('penalty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['gl_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gl_transfer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gl_transfer_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gl_transfer_round_id'), ['round_id'], unique=False)

    op.create_table('ms_constructor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('ext_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('short', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['ms_season.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'ext_id')
    )
    with op.batch_alter_table('ms_constructor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ms_constructor_ext_id'), ['ext_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ms_constructor_season_id'), ['season_id'], unique=False)

    op.create_table('ms_race_weekend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_sprint', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['ms_circuit.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['ms_season.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'round')
    )
    with op.batch_alter_table('ms_race_weekend', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ms_race_weekend_round'), ['round'], unique=False)
        batch_op.create_index(batch_op.f('ix_ms_race_weekend_season_id'), ['season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ms_race_weekend_slug'), ['slug'], unique=False)

    op.create_table('gl_league_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['gl_league.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['gl_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'profile_id')
    )
    with op.batch_alter_table('gl_league_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gl_league_member_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gl_league_member_profile_id'), ['profile_id'], unique=False)

    op.create_table('ms_driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('ext_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('abbreviation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('constructor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['ms_constructor.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['ms_season.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'ext_id')
    )
    with op.batch_alter_table('ms_driver', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ms_driver_ext_id'), ['ext_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ms_driver_season_id'), ['season_id'], unique=False)

    op.create_table('ms_race_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekend_id', sa.Integer(), nullable=False),
    sa.Column('ext_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['weekend_id'], ['ms_race_weekend.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weekend_id', 'kind')
    )
    with op.batch_alter_table('ms_race_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ms_race_session_ext_id'), ['ext_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ms_race_session_weekend_id'), ['weekend_id'], unique=False)

    op.create_table('ms_lap_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('lap_duration', sa.Float(), nullable=True),
    sa.Column('sector1', sa.Float(), nullable=True),
    sa.Column('sector2', sa.Float(), nullable=True),
    sa.Column('sector3', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['ms_driver.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['ms_race_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'driver_id', 'lap_number')
    )
    with op.batch_alter_table('ms_lap_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ms_lap_result_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ms_lap_result_session_id'), ['session_id'], unique=False)

    op.create_table('ms_pit_stop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('pit_duration', sa.Float(), nullable=True),
    sa.Column('stop_duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['ms_driver.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['ms_race_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'driver_id', 'lap_number')
    )
    with op.batch_alter_table('ms_pit_stop', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ms_pit_stop_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ms_pit_stop_session_id'), ['session_id'], unique=False)

    op.create_table('ms_race_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('lap_number', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['ms_race_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('ms_race_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ms_race_event_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_ms_race_event_session_id'), ['session_id'], unique=False)

    op.create_table('ms_session_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fastest_lap', sa.Boolean(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['ms_driver.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['ms_race_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'driver_id')
    )
    with op.batch_alter_table('ms_session_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ms_session_result_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ms_session_result_session_id'), ['session_id'], unique=False)

    op.create_table('ms_starting_grid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('grid_position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['ms_driver.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['ms_race_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'driver_id')
    )
    with op.batch_alter_table('ms_starting_grid', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ms_starting_grid_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ms_starting_grid_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ms_starting_grid', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ms_starting_grid_session_id'))
        batch_op.drop_index(batch_op.f('ix_ms_starting_grid_driver_id'))

    op.drop_table('ms_starting_grid')
    with op.batch_alter_table('ms_session_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ms_session_result_session_id'))
        batch_op.drop_index(batch_op.f('ix_ms_session_result_driver_id'))

    op.drop_table('ms_session_result')
    with op.batch_alter_table('ms_race_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ms_race_event_session_id'))
        batch_op.drop_index(batch_op.f('ix_ms_race_event_idempotency_key'))

    op.drop_table('ms_race_event')
    with op.batch_alter_table('ms_pit_stop', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ms_pit_stop_session_id'))
        batch_op.drop_index(batch_op.f('ix_ms_pit_stop_driver_id'))

    op.drop_table('ms_pit_stop')
    with op.batch_alter_table('ms_lap_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ms_lap_result_session_id'))
        batch_op.drop_index(batch_op.f('ix_ms_lap_result_driver_id'))

    op.drop_table('ms_lap_result')
    with op.batch_alter_table('ms_race_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ms_race_session_weekend_id'))
        batch_op.drop_index(batch_op.f('ix_ms_race_session_ext_id'))

    op.drop_table('ms_race_session')
    with op.batch_alter_table('ms_driver', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ms_driver_season_id'))
        batch_op.drop_index(batch_op.f('ix_ms_driver_ext_id'))

    op.drop_table('ms_driver')
    with op.batch_alter_table('gl_league_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gl_league_member_profile_id'))
        batch_op.drop_index(batch_op.f('ix_gl_league_member_league_id'))

    op.drop_table('gl_league_member')
    with op.batch_alter_table('ms_race_weekend', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ms_race_weekend_slug'))
        batch_op.drop_index(batch_op.f('ix_ms_race_weekend_season_id'))
        batch_op.drop_index(batch_op.f('ix_ms_race_weekend_round'))

    op.drop_table('ms_race_weekend')
    with op.batch_alter_table('ms_constructor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ms_constructor_season_id'))
        batch_op.drop_index(batch_op.f('ix_ms_constructor_ext_id'))

    op.drop_table('ms_constructor')
    with op.batch_alter_table('gl_transfer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gl_transfer_round_id'))
        batch_op.drop_index(batch_op.f('ix_gl_transfer_profile_id'))

    op.drop_table('gl_transfer')
    with op.batch_alter_table('gl_team_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gl_team_snapshot_round_id'))
        batch_op.drop_index(batch_op.f('ix_gl_team_snapshot_profile_id'))

    op.drop_table('gl_team_snapshot')
    with op.batch_alter_table('gl_team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gl_team_profile_id'))

    op.drop_table('gl_team')
    with op.batch_alter_table('gl_refresh_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gl_refresh_token_token_hash'))
        batch_op.drop_index(batch_op.f('ix_gl_refresh_token_profile_id'))

    op.drop_table('gl_refresh_token')
    with op.batch_alter_table('gl_league', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gl_league_code'))

    op.drop_table('gl_league')
    with op.batch_alter_table('gl_boost_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gl_boost_usage_profile_id'))

    op.drop_table('gl_boost_usage')
    with op.batch_alter_table('ms_season', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ms_season_year'))

    op.drop_table('ms_season')
    op.drop_table('ms_data_sync_run')
    with op.batch_alter_table('ms_circuit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ms_circuit_ext_id'))

    op.drop_table('ms_circuit')
    with op.batch_alter_table('gl_score_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gl_score_event_session_id'))
        batch_op.drop_index(batch_op.f('ix_gl_score_event_season_id'))
        batch_op.drop_index(batch_op.f('ix_gl_score_event_round_id'))
        batch_op.drop_index(batch_op.f('ix_gl_score_event_profile_id'))

    op.drop_table('gl_score_event')
    with op.batch_alter_table('gl_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gl_profile_username'))
        batch_op.drop_index(batch_op.f('ix_gl_profile_email'))

    op.drop_table('gl_profile')
    # ### end Alembic commands ###
